export const NORMALIZE_COURSE: Record<string, string> = {
    // AD / AI / ML / DS Mappings (2025 & Historical)
    "AD Artificial Intel, Data Sc": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE": "AI & Data Science",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND DATA SCIENCE": "AI & Data Science",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND DATA SCIENCE ": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING": "CS - AI & Machine Learning",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING": "CS - AI & Machine Learning",
    "AI Artificial Intelligence": "AI & Data Science",
    "B TECH IN ARTIFICIAL INTELLIGENCE": "AI & Data Science",
    "B.TECH IN COMPUTER SCIENCE AND ARTIFICIAL INTELLIGENCE": "CS - Artificial Intelligence",

    // Data Science Wildcards
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(DAT A SCIENCE)": "CS - Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(DAT A SCIENCE)": "CS - Data Science",
    "B TECH (HONS) COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "CS Data Science": "CS - Data Science",
    "DS Comp. Sc. Engg- Data Sc.": "CS - Data Science",
    "DATA SCIENCES": "CS - Data Science",
    "DATA SCIENCE": "CS - Data Science",
    "DC Data Sciences": "CS - Data Science",
    "BZ B Tech in DS": "CS - Data Science",
    "BF B Tech in DS": "CS - Data Science",
    "LD B Tech in DS": "CS - Data Science",

    // Biotechnology
    "BT Bio Technology": "Biotechnology",
    "BIO- TECHNOLOGY": "BIO-TECHNOLOGY",
    "B TECH IN BIO- TECHNOLOGY": "Biotechnology",
    "B.Tech In BIOTECHNOLOG Y & BIO- ENGINEERING": "Biotechnology",
    "B.Tech In BIOTECHNOLOGY & BIO- ENGINEERING": "Biotechnology",
    "BIOTECHNOLOGY": "BIO-TECHNOLOGY",

    // Computer Science & Core
    "CS Computers": "Computer Science & Engineering",
    "COMPUTER SCIENCE AND ENGINEERING": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE": "Computer Science & Engineering",
    "CS-Computer Science": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE & ENGG (ARTIFICIAL INTELLIGENCE AND FUTURE TECHNOLOGIES )": "CS - AI & Future Tech",
    "B TECH IN COMPUTER SCIENCE & ENGG (ARTIFICIAL INTELLIGENCE AND FUTURE TECHNOLOGIES)": "CS - AI & Future Tech",
    "B TECH IN COMPUTER SCIENCE & ENGINEERING (ARTIFICAL INTELLIGENCE & MACHINE LEARNING)": "CS - AI & Machine Learning",
    "B TECH IN COMPUTER SCIENCE (CLOUD COMPUTING)": "CS - Cloud Computing",
    "B TECH IN COMPUTER SCIENCE (CYBER SECURITY)": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "B TECH IN COMPUTER SCIENCE (DATA SCIENCE)": "CS - Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(A RTIFICIAL INTELLIGENCE AND DATA SCIENCE)": "AI & Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(ARTI FICIAL INTELLIGENCE AND DATA SCIENCE)": "AI & Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(B LOCK CHAIN)": "CS - Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(BLO CK CHAIN)": "CS - Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(C YBER SECURITY)": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(CYB ER SECURITY)": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(I OT INCLUDING BLOCK CHAIN)": "CS - IoT & Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(I OT)": "CS - IoT",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(IOT INCLUDING BLOCK CHAIN)": "CS - IoT & Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(IOT)": "CS - IoT",
    "B TECH IN COMPUTER SCIENCE AND INFORMATION TECHNOLOGY": "CS & Info Tech",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY": "CS & Technology",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(B IG DATA)": "CS - Big Data",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(BIG DATA)": "CS - Big Data",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(D EV OPS)": "CS - DevOps",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(DEV OPS)": "CS - DevOps",
    "B Tech in Computer Science (Information Security)": "CS - Information Security",
    "B.TECH IN COMPUTER ENGINEERING(S OFTWARE PRODUCT DEVELOPMENT)": "CS - Software Product Dev",
    "B.TECH IN COMPUTER ENGINEERING(SOF TWARE PRODUCT DEVELOPMENT)": "CS - Software Product Dev",
    "B.TECH IN COMPUTER SCIENCE AND ENGG (ROBOTICS)": "CS - Robotics",
    "B.TECH IN COMPUTER SICENCE AND ENGG (DATA ANALYTICS)": "CS - Data Analytics",
    "B.Tech in COMPUTER SCIENCE & ENGG (Business Systems)": "CS - Business Systems",
    "B.Tech in Computer Science (Internet of Things)": "CS - IoT",
    "B.Tech in Computer Science and Engineering(Clou d Computing)": "CS - Cloud Computing",
    "B.Tech in Computer Science and Engineering(Cloud Computing)": "CS - Cloud Computing",
    "B.Tech in Computer Science and Engineering(Dev Ops)": "CS - DevOps",
    "B.Tech in Computer Science and Engineering(Full Stack Development)": "CS - Full Stack Dev",
    "COMPUTER SCIENCE": "Computer Science & Engineering",
    "COMPUTER SCIENCE & TECHNOLOGY": "CS & Technology",
    "COMPUTER SCIENCE AND BUSINESS SYSTEMS": "CS - Business Systems",
    "COMPUTER SCIENCE AND DESIGN": "CS - Design",
    "BTECH IN COMPUTER SCIENCE AND BUSINESS SYSTEMS": "CS - Business Systems",
    "BTECH IN COMPUTER SCIENCE AND DESIGN": "CS - Design",
    "CB Comp. Sc. and Bus Sys.": "CS - Business Systems",
    "DL B.TECH IN CS": "Computer Science & Engineering",
    "DM B.TECH IN CS NW": "CS - Networks",
    "BW B Tech in CS": "Computer Science & Engineering",

    // AI & ML (Additional Mappings)
    "CA CS (AI, Machine Learning)": "CS - AI & Machine Learning",
    "AIML": "CS - AI & Machine Learning",
    "B Tech in Computer Science(AI &ML)": "CS - AI & Machine Learning",
    "BH B Tech in AI": "AI & Data Science",
    "COMPUTER SCIENCE AND ENGG (ARTIFICIAL INTELLIGENCE)": "CS - Artificial Intelligence",
    "COMPUTER SCIENCE AND ENGG(ARTIFICIA L INTELLIGENCE AND MACHINE LEARNING)": "CS - AI & Machine Learning",
    "COMPUTER SCIENCE AND ENGG(ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)": "CS - AI & Machine Learning",
    "COMPUTER APPLICATIONS": "COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)",
    "CYBER SECURITY": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "CY C. Cyber Security": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "CY CS - Cyber Security": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "CY C.S. Cyber Security": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "CY CS- Cyber Security": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "CS - Cyber Security": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
    "COMPUTER SCIENCE AND ENGINEERING (AIML)": "CS - AI & Machine Learning",
    "CD Computer Sc. and Disgn": "COMPUTER SCIENCE AND DESIGN",
    "CS - Business Systems.": "COMPUTER SCIENCE AND BUSINESS SYSTEMS",
    "COMPUTER SCIENCE AND ENGINEERING(A RTIFICAL INTELLIGENCE & DATA SCIENCE)": "AI & Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(ARTI FICAL INTELLIGENCE & DATA SCIENCE)": "AI & Data Science",

    // Electronics & Others
    "EC Electronics": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATION ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMMUNICATION ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMMUNICATIO N ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMPUTER ENGINEERING": "Electronics & Computer Engg",
    "B.TECH IN ELECTRONICS ENGINEERING": "Electronics Engineering",
    "B.TECH IN ELECTRONICS ENGINEERING (VLSI AND EMBEDDED SYSTEM)": "Electronics - VLSI & Embedded",
    "B.TECH IN EMBEDDED SYSTEM AND VLSI": "Electronics - VLSI & Embedded",
    "BTECH IN ELECTRONICS ENGINEERING(V LSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "BTECH IN ELECTRONICS ENGINEERING(VLSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS & COMMUNICATION ENGINEERING(IND USTRIAL INTEGTATED)": "Electronics & Comm (Ind. Integ)",
    "ELECTRONICS & COMPUTER ENGINEERING": "Electronics & Computer Engg",
    "ELECTRONICS & COMPUTER SCIENCE": "Electronics & Computer Science",
    "ELECTRONICS & INSTRUMENTATI ON ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS & INSTRUMENTATION ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND COMMUNICATIO N (ADVANCED COMMUNICATIO N TECHNOLOGY)": "Electronics - Advanced Comm",
    "ELECTRONICS AND COMMUNICATIO N ENGG": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATIO N ENGG (VLSI DESIGN AND TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS AND COMMUNICATION (ADVANCED COMMUNICATION TECHNOLOGY)": "Electronics - Advanced Comm",
    "ELECTRONICS AND COMMUNICATION ENGG": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATIO N ENGINEERING": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATION ENGG (VLSI DESIGN AND TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS AND INSTRUMENTATI ON ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND INSTRUMENTATION ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND TELECOMMUNIC ATION ENGINEERING": "Electronics & Telecommunication",
    "ELECTRONICS AND TELECOMMUNICAT ION ENGINEERING": "Electronics & Telecommunication",
    "ELECTRONICS ENGINEERING(V LSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS ENGINEERING(VLSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "BB B Tech in EC": "Electronics & Communication",

    // Information Science
    "IE Info.Science": "Information Science",
    "INFORMATION SCIENCE AND ENGINEERING": "Information Science",
    "B TECH IN INFORMATION SCIENCE & TECHNOLOGY": "Information Science",
    "B TECH IN INFORMATION SCIENCE ENGINEERING": "Information Science",
    "INFORMATION SCIENCE": "Information Science",
    "Information Science": "Information Science",
    "IZ INFORMATION SCIENCE": "Information Science",
    "CU B Tech in IS": "Information Science",

    // Mechanical
    "ME Mechanical": "Mechanical Engineering",
    "MECHANICAL ENGINEERING": "Mechanical Engineering",
    "B TECH IN MECHANICAL ENGINEERING": "Mechanical Engineering",
    "B TECH IN MECHATRONICS ENGINEERING": "Mechatronics",
    "B TECH IN ROBOTIC ENGINEERING": "Robotics",
    "B TECH IN ROBOTICS AND AUTOMATION": "Robotics & Automation",
    "B TECH IN ROBOTICS ENGINEERING": "Robotics",
    "B Tech in ROBOTICS AND ARTIFICIAL INTELLIGENCE": "Robotics & AI",
    "B.TECH IN MECHANICAL AND AEROSPACE ENGINEERING": "Mechanical & Aerospace",
    "BTECH IN MECHANICAL AND SMART MANUFACTURING": "Mechanical & Smart Mfg",
    "DB B Tech in ME": "Mechanical Engineering",

    // Civil
    "CE Civil": "Civil Engineering",
    "CIVIL ENGINEERING": "Civil Engineering",
    "B TECH IN CIVIL ENGINEERING": "Civil Engineering",
    "B.TECH IN CIVIL CONSTRUCTION AND SUSTAINABILITY ENGINEERING": "Civil - Const. & Sustainability",
    "CIVIL ENGINEERING (KANNADA MEDIUM)": "Civil Engineering (Kannada)",
    "CIVIL ENGINEERING WITH COMPUTER APPLICATION": "Civil - Computer App",
    "CIVIL ENVIRONMENTA L ENGINEERING": "Civil - Environmental",
    "CIVIL ENVIRONMENTAL ENGINEERING": "Civil - Environmental",
    "CK Civil Engg (Kannada)": "Civil Engineering (Kannada)",
    "CV Civil Environment Engg": "Civil - Environmental",
    "BP B Tech in CE": "Civil Engineering",

    // Others
    "SE Aero Space Engg": "AERO SPACE ENGINEERING",
    "SE Aero Space Engg.": "AERO SPACE ENGINEERING",
    "SE Aero Space Engs.": "AERO SPACE ENGINEERING",
    "AE Aeronaut.Engg": "Aeronautical Engineering",
    "AU Automobile": "Automobile Engineering",
    "CH Chemical": "Chemical Engineering",
    "EE Electrical": "Electrical & Electronics",
    "IT Instrument. Tech.": "Instrumentation Technology",
    "AERO SPACE ENGINEERING": "AERO SPACE ENGINEERING",
    "AEROSPACE ENGINEERING": "AERO SPACE ENGINEERING",
    "AERONAUTICAL ENGINEERING": "Aeronautical Engineering",
    "AGRICULTURE ENGINEERING": "Agricultural Engineering",
    "AUTOMATION AND ROBOTICS": "Automation & Robotics",
    "AUTOMOBILE ENGINEERING": "Automobile Engineering",
    "AUTOMOTIVE ENGINEERING": "Automotive Engineering",
    "BIO-MEDICAL ENGINEERING": "Biomedical Engineering",
    "BIOMEDICAL AND ROBOTIC ENGINEERING": "Biomedical & Robotic",
    "CHEMICAL ENGINEERING": "Chemical Engineering",
    "CONSTRUCTION TECHNOLOGY AND MGMT": "Construction Tech & Mgmt",
    "ELECTRICAL & COMPUTER ENGINEERING": "Electrical & Computer Engg",
    "ELECTRICAL & ELECTRONICS ENGINEERING": "Electrical & Electronics",
    "ELECTRICAL AND ELECTRONICS ENGINEERING": "Electrical & Electronics",
    "EI Elec. Inst. Engg": "Electronics & Instrumentation",
    "ET Elec. Telecommn. Engg.": "Electronics & Telecommunication",
    "ET Elec. Telecomm. Engg.": "Electronics & Telecommunication",
    "ELECTRONICS AND INSTRUMENTATION ENGG": "Electronics & Instrumentation",
    "INDUSTRIAL & PRODUCTION ENGINEERING": "Industrial & Production",
    "INDUSTRIAL ENGINEERING & MANAGEMENT": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "INDUSTRIAL ENGINEERING AND MANAGEMENT": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "INDUSTRIAL ENGINEERING AND MANAGEMENT'": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "IM Ind. Engg. Mgmt.": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "IM Ind. Engg. Mgmt": "INDUSTRIAL ENGINEERING & MANAGEMENT",
};

export const normalizeCourseName = (rawName: string) => {
    if (!rawName) return "";
    const cleaned = rawName.replace(/\n/g, ' ').replace(/\s+/g, ' ').trim();
    return NORMALIZE_COURSE[cleaned] || cleaned;
};
